# Assignment_1
If you copy codes from previous answers, explain each step. No explanation is `0 points`.

##  Part 1.Data types


a.Declare one variable for each one these types: : int , float , string , boolean.
- Print  the varible's type using  type () function




 b. Using only the following inputs: ```5``` and ```2```  ,  work the  operators to get the output  : ```50```

c. Evaluate if the output of the previous excercise is over 100. Create a variable that makes this evaluation. (Hint: It would be a boolean).

d. Create a variable equal to a list that contains: 
- a string,
- a boolean,
- two numeric values ( of any kind)  and
- a  list of two strings with the names of your favourite musical artists. 

## Part 2. Containers

e. Create a tuple with 3 elements. Explain why you can't modify it. 

f.Create a dictionary with at least 3 different  keys and values .

g.We got the next courses list: 

In [24]:
courses = ["History", "Economy", "Anthropology", "Sociology ", "Literature"]

g.1.Add tree additional courses in 3 different ways( one for each way):
   - Sum (+) a list that contains an additional course. 
   - Use append. 
   - Use extend. 

g.2.Use the indexation to stress _Sociology_.

g.3 Remove your least favourite course

g.4. Invert the list

h.Create a dictionary that representst a fruits inventory:
 - Add at least 5 fruits to the inventory
- Print the amount of apples in stock 
- Modify the amount of grapes


i.  Write a dictionary with the local GMT of the nexts cities:
- Antananarivo, Madagascar, 
- Beirut, Lebanon, 
- Jakarta, Indonesia, 
- Teherán, Iran, 
- Vientiane, Laos, 



Hint: Lima would be: `"Lima": -5`

 j.Add the nexts cities to the dictionary:
- Astana, Kazakhstan,
- Uagadugú, Burkina Faso,
- Balmopan, Belize

# Part 3. Numpy


k.Create an array with 10 aleatory values that go from 0 to 9

In [25]:
import numpy as np #imports the library and and aliases it as np

In [26]:
random = np.random.randint(1, 11, 10) # This code creates a list of 10 random integers, where the lowest value is 1 and the highest value is 10. The last component of the code refers to the size or number of elements in the list, which is 10.
print(random) #display the list created above

[10  9  2  4  2  9 10  1  2  6]


l.Create a matrix 3x2 fill with zeros

In [27]:
Matrix = np.zeros((3, 2)) # This code creates a 3-row by 2-column matrix filled with zeros.
print(Matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


m.Sum two arrays and then multiply the output by an scalar

In [28]:
a = np.array([[1,7,4], [3,5,7]]) #create array 'a' with 2 rows and 3 columns
print(a)

[[1 7 4]
 [3 5 7]]


In [29]:
b = np.array([[3,5,9], [0,7,8]]) #create array 'b' 
print(b)

[[3 5 9]
 [0 7 8]]


In [30]:
sum = a + b #sum a-array and b-array
result = sum * 7 #multiply by a scalar, in this case, 7. 
print("Sum of array:", sum) 
print("Result with scalar:", result)

Sum of array: [[ 4 12 13]
 [ 3 12 15]]
Result with scalar: [[ 28  84  91]
 [ 21  84 105]]


n.Create 2 arrays with the values that you wish :
- Concatenate vertically 
- Concatenate horizontally 

In [31]:
x= np.array([[2,8],[5,0]]) #create a 2x2 array called "x"
x

array([[2, 8],
       [5, 0]])

In [32]:
y= np.array([[4,1],[9,7],[4,8]]) #create a 2x2 array called "y"
y

array([[4, 1],
       [9, 7],
       [4, 8]])

In [33]:
np.concatenate( (x, y) , axis = 0) #concatenate arrays 'x' and 'y' along rows

array([[2, 8],
       [5, 0],
       [4, 1],
       [9, 7],
       [4, 8]])

In [34]:
y_2= y.reshape(2,3) #reshape array 'y' from 3x2 to 2x3
y_2

array([[4, 1, 9],
       [7, 4, 8]])

In [35]:
np.concatenate( (x, y_2) , axis = 1) #concatenate array 'x' and array 'y_2' along colums

array([[2, 8, 4, 1, 9],
       [5, 0, 7, 4, 8]])