# Assignment_1
If you copy codes from previous answers, explain each step. No explanation is `0 points`.

##  Part 1.Data types


a.Declare one variable for each one these types: : int , float , string , boolean.
- Print  the varible's type using  type () function




In [2]:
var_int = 20 
var_int

20

type (var_int ) ## I use the "type" function to know what data type the previously defined variable is.

In [5]:
var_float = 23.5
var_float

23.5

In [7]:
type(var_float) ## I use the "type" function to know what data type the previously defined variable is.

float

In [9]:
string = "This is a string"
string

'This is a string'

In [11]:
type(string) ## I use the "type" function to know what data type the previously defined variable is.

str

In [13]:
var_bool = False
var_bool

False

In [15]:
type(var_bool) ## I use the "type" function to know what data type the previously defined variable is.

bool

 b. Using only the following inputs: ```5``` and ```2```  ,  work the  operators to get the output  : ```50```

In [18]:
output = 2 * (5 **2)
output

50

c. Evaluate if the output of the previous excercise is over 100. Create a variable that makes this evaluation. (Hint: It would be a boolean).

In [21]:
print(output > 100)

False


d. Create a variable equal to a list that contains: 
- a string,
- a boolean,
- two numeric values ( of any kind)  and
- a  list of two strings with the names of your favourite musical artists. 

In [24]:
list_a = ["My first list", True, 21, 48.7,["Liam Gallagher", "Steven Taylor"] ]
list_a

['My first list', True, 21, 48.7, ['Liam Gallagher', 'Steven Taylor']]

In [26]:
list_1 = ["My first list", True, 21, 48.7] ## I created a list with the first values
list_1

['My first list', True, 21, 48.7]

In [28]:
list_2= ["Liam Gallagher", "Steven Taylor"] ##I created a list of two strings with the names of your favourite musical artists. 
list_2

['Liam Gallagher', 'Steven Taylor']

In [30]:
list_1.extend(list_2) ## I use the "extend" function to merge the two lists
list_1

['My first list', True, 21, 48.7, 'Liam Gallagher', 'Steven Taylor']

## Part 2. Containers

e. Create a tuple with 3 elements. Explain why you can't modify it. 

In [34]:
tuple = (19, "Marzo", 3.1415) #using () to create a tuple, Tuples are immutable, their contents cannot be changed once they are created
tuple

(19, 'Marzo', 3.1415)

f.Create a dictionary with at least 3 different  keys and values .

In [37]:
dict = {"name": "Alice","age": 25,"city": "New York"}  #using {} to create a dictionary
dict

{'name': 'Alice', 'age': 25, 'city': 'New York'}

g.We got the next courses list: 

In [40]:
courses = ["History", "Economy", "Anthropology", "Sociology ", "Literature"]

g.1.Add tree additional courses in 3 different ways( one for each way):
   - Sum (+) a list that contains an additional course. 
   - Use append. 
   - Use extend. 

In [43]:
courses = courses + ["Philosophy"] #for sum
courses.append("Mathematics") #for append
courses.extend(["Biology"]) #for extend
courses

['History',
 'Economy',
 'Anthropology',
 'Sociology ',
 'Literature',
 'Philosophy',
 'Mathematics',
 'Biology']

g.2.Use the indexation to stress _Sociology_.

In [46]:
courses[3] = courses[3].upper() #stress Sociology
courses

['History',
 'Economy',
 'Anthropology',
 'SOCIOLOGY ',
 'Literature',
 'Philosophy',
 'Mathematics',
 'Biology']

g.3 Remove your least favourite course

In [49]:
leastfavcourse = "Anthropology" #remove 1 course
courses.remove(leastfavcourse)
courses

['History',
 'Economy',
 'SOCIOLOGY ',
 'Literature',
 'Philosophy',
 'Mathematics',
 'Biology']

g.4. Invert the list

In [52]:
courses.reverse() #invert courses
courses

['Biology',
 'Mathematics',
 'Philosophy',
 'Literature',
 'SOCIOLOGY ',
 'Economy',
 'History']

h.Create a dictionary that representst a fruits inventory:
 - Add at least 5 fruits to the inventory
- Print the amount of apples in stock 
- Modify the amount of grapes


In [55]:
fruits_inventory = {"apples": 10,"bananas": 15,"oranges": 8,"grapes": 20,"pears": 12} #list of fruits
fruits_inventory

{'apples': 10, 'bananas': 15, 'oranges': 8, 'grapes': 20, 'pears': 12}

In [57]:
fruits_inventory["grapes"] = 25 #modify amount of grapes
fruits_inventory

{'apples': 10, 'bananas': 15, 'oranges': 8, 'grapes': 25, 'pears': 12}

i.  Write a dictionary with the local GMT of the nexts cities:
- Antananarivo, Madagascar, 
- Beirut, Lebanon, 
- Jakarta, Indonesia, 
- Teherán, Iran, 
- Vientiane, Laos, 



Hint: Lima would be: `"Lima": -5`

In [60]:
gmt_cities = {"Antananarivo": 3,"Beirut": 2,"Jakarta": 7,"Teherán": 3.5,"Vientiane": 7}
gmt_cities

{'Antananarivo': 3, 'Beirut': 2, 'Jakarta': 7, 'Teherán': 3.5, 'Vientiane': 7}

 j.Add the nexts cities to the dictionary:
- Astana, Kazakhstan,
- Uagadugú, Burkina Faso,
- Balmopan, Belize

In [63]:
gmt_cities["Astana"] = 6
gmt_cities["Uagadugú"] = 0
gmt_cities["Balmopan"] = -6
gmt_cities

{'Antananarivo': 3,
 'Beirut': 2,
 'Jakarta': 7,
 'Teherán': 3.5,
 'Vientiane': 7,
 'Astana': 6,
 'Uagadugú': 0,
 'Balmopan': -6}

# Part 3. Numpy


In [84]:
import numpy as np

k.Create an array with 10 aleatory values that go from 0 to 9

In [91]:
# For this task we use np.random.randint in order to get integer random values
array_ale = np.random.randint(0, 10, 10)
array_ale

array([7, 7, 4, 7, 1, 7, 0, 9, 2, 8])

l.Create a matrix 3x2 fill with zeros

In [94]:
matrix_zero = np.zeros((3,2))
matrix_zero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

m.Sum two arrays and then multiply the output by an scalar

In [97]:
# Create two random arrays with 5 values from 0 to 5 
X = np.random.randint(0, 6, 5)
Y = np.random.randint(0, 6, 5)
# We see our arrays created
print(X)
print(Y)

[4 2 2 4 0]
[4 4 0 0 4]


In [99]:
# Sum the two arrays and see the result
sum_arrays = X + Y
sum_arrays 

array([8, 6, 2, 4, 4])

n.Create 2 arrays with the values that you wish :
- Concatenate vertically 
- Concatenate horizontally 

In [102]:
# Create two arrays
A = np.array([2, 5, 9, 0, 3])
B = np.array([5, 1, 4, 8, 6])
print(A)
print(B)

[2 5 9 0 3]
[5 1 4 8 6]


In [104]:
# Vertical concatenation using method vstack
vertical = np.vstack((A, B))
vertical

array([[2, 5, 9, 0, 3],
       [5, 1, 4, 8, 6]])

In [106]:
# Horizontal concatenation using method hstack
horizontal = np.hstack((A, B)) 
horizontal

array([2, 5, 9, 0, 3, 5, 1, 4, 8, 6])